### ISSUE TITLE
Параметр strategy для i18n в nuxt.config.ts не учитывается при запуске проекта в режиме разработки

### ISSUE THREAD

**Issue by mikebreadwater** [bezumkin/vesp#3]
## Ожидаемое поведение
Параметр strategy в файле frontend/nuxt.config.ts учитывается и в url каждой страницы добавляется языковой префикс
``` javascript
...
i18n: {
    strategy: 'prefix',
    customRoutes: 'config',
    pages: {
      admin: false,
      user: false,
    },
    trailingSlash: true,
    locales,
    defaultLocale: locales[1].code,
    detectBrowserLanguage: {
      fallbackLocale: locales[0].code,
    },
  },
...
```

## Текущее поведение
В файл frontend/.nuxt/i18n.options.mjs параметр strategy не меняется.
```javascript
  ...
  "trailingSlash": true,  // меняется
  ...
  "strategy": "no_prefix",  // не меняется
  ...
  "customRoutes": "config", // меняется
  "pages": {  // меняется
    "admin": false,
    "user": false
  },
```

## Возможное решение
Перенести параметр `strategy: 'no_prefix'` из файла frontend/node_modules/@vesp/frontend/dist/module.mjs в frontend/nuxt.config.ts
Проверил, если данного параметра нет, то он учитывается и появляется возможность им управлять.

## Шаги для воспроизведения

1. Клонируем репозиторий
2. В файле src/frontend/nuxt.config.ts добавляем `strategy: 'prefix'` для i18n
3. Переименовываем docker-compose.override.yml.dist в docker-compose.override.yml
4. Запускаем docker docker-compose up --build

## Контекст (окружение)

- Windows 11 Pro 21H2
- WSL 2 Ubuntu 22.04.3 LTS
- Docker 4.33.1 (161083)

**Comment by bezumkin** [comment]
Проблема в работе `@vesp/frontend` вместе с `@nuxtjs/i18n`.

Он устанавливает и настраивает i18n, при этом в нём прописаны [настройки по умолчанию](https://github.com/bezumkin/vesp-frontend/blob/main/src/module.ts#L33-L39) вместе с `no_prefix`, которые можно поменять в конфиге `vesp.i18n`.

И всё было бы хорошо, через эти настройки [модуль накста не принимает локали](https://github.com/bezumkin/vesp-frontend/blob/main/src/module.ts#L72) - он их там у себя грузит только из явного указания в основных настройках.

Вот и получается, что для правильной работы делать вот так:
```js
export default {
  // ...
  modules: ['@vesp/frontend'],
  vesp: {
    icons: {solid: ['faUser', 'faPowerOff', 'faRightToBracket']},
    i18n: {strategy: 'prefix'}, // Меняем стратегию по умолчанию
  },
  i18n: {
    // Добавляем все остальные опции
    locales,
    customRoutes: 'config',
    pages: {
      admin: false,
      user: false,
    },
    trailingSlash: true,
    defaultLocale: locales[0].code || 'en',
    detectBrowserLanguage: {
      fallbackLocale: locales[0].code || 'en',
    },
  },
}
```

То есть, локали обязательно указывать только в настройки модуля `i18n`, стратегию только в настройки `vesp.i18n`. А всё остальное - хоть туда, хоть сюда.

Что с этим делать - не знаю. 

Убирать `no_prefix` по умолчанию у `@vesp/frontend` не хочется, это сломает обратную совместимость.

По-хорошему, надо фиксить [модуль @nuxtjs/i18n](https://github.com/nuxt-modules/i18n/blob/main/src/module.ts), потому что это его косяк, что он не читает явно переданные локали при установке модуля. Но у меня времени на исправление пока нет.

Поэтому предлагаю воспользоваться указанным выше решением.

**Comment by mikebreadwater** [comment]
@bezumkin Спасибо за решение! Про обратную совместимость вообще не подумал, в будущем буду учитывать.
